include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/*/*.g.dart
    - lib/*/*.mapper.dart
linter:
  rules:
    sort_pub_dependencies: true
    always_declare_return_types: true
    public_member_api_docs: false
    invalid_case_patterns: true
    use_super_parameters: true
    unnecessary_null_checks: true
    sort_constructors_first: true
    unnecessary_parenthesis: true
    use_colored_box: true
    use_decorated_box: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    prefer_single_quotes: true
    require_trailing_commas: true
