name: gooddeeds
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^8.2.0
  go_router: ^16.2.1
  injectable: ^2.0.3
  intl: any
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  build_runner: ^2.7.1
  flutter_gen_runner: ^5.12.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  go_router_builder: ^4.1.0
  injectable_generator: ^2.0.3

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
